# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mixer_pb2 as mixer__pb2


class MixerStub(object):
    """
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnqueueCommand = channel.unary_unary(
                '/proto.Mixer/EnqueueCommand',
                request_serializer=mixer__pb2.EnqueueRequest.SerializeToString,
                response_deserializer=mixer__pb2.EnqueueResponse.FromString,
                )


class MixerServicer(object):
    """
    """

    def EnqueueCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MixerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnqueueCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueCommand,
                    request_deserializer=mixer__pb2.EnqueueRequest.FromString,
                    response_serializer=mixer__pb2.EnqueueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Mixer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mixer(object):
    """
    """

    @staticmethod
    def EnqueueCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Mixer/EnqueueCommand',
            mixer__pb2.EnqueueRequest.SerializeToString,
            mixer__pb2.EnqueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
