# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mixer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmixer.proto\x12\x05proto\"4\n\x0e\x45nqueueRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"8\n\x0f\x45nqueueResponse\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x12\n\nreceipt_id\x18\x02 \x01(\t2J\n\x05Mixer\x12\x41\n\x0e\x45nqueueCommand\x12\x15.proto.EnqueueRequest\x1a\x16.proto.EnqueueResponse\"\x00\x42&Z$github.com/guycole/elder-mixer/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mixer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/guycole/elder-mixer/proto'
  _globals['_ENQUEUEREQUEST']._serialized_start=22
  _globals['_ENQUEUEREQUEST']._serialized_end=74
  _globals['_ENQUEUERESPONSE']._serialized_start=76
  _globals['_ENQUEUERESPONSE']._serialized_end=132
  _globals['_MIXER']._serialized_start=134
  _globals['_MIXER']._serialized_end=208
# @@protoc_insertion_point(module_scope)
