// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: mixer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Mixer_EnqueueCommand_FullMethodName = "/proto.Mixer/EnqueueCommand"
)

// MixerClient is the client API for Mixer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MixerClient interface {
	EnqueueCommand(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
}

type mixerClient struct {
	cc grpc.ClientConnInterface
}

func NewMixerClient(cc grpc.ClientConnInterface) MixerClient {
	return &mixerClient{cc}
}

func (c *mixerClient) EnqueueCommand(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, Mixer_EnqueueCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MixerServer is the server API for Mixer service.
// All implementations must embed UnimplementedMixerServer
// for forward compatibility
type MixerServer interface {
	EnqueueCommand(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	mustEmbedUnimplementedMixerServer()
}

// UnimplementedMixerServer must be embedded to have forward compatible implementations.
type UnimplementedMixerServer struct {
}

func (UnimplementedMixerServer) EnqueueCommand(context.Context, *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnqueueCommand not implemented")
}
func (UnimplementedMixerServer) mustEmbedUnimplementedMixerServer() {}

// UnsafeMixerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MixerServer will
// result in compilation errors.
type UnsafeMixerServer interface {
	mustEmbedUnimplementedMixerServer()
}

func RegisterMixerServer(s grpc.ServiceRegistrar, srv MixerServer) {
	s.RegisterService(&Mixer_ServiceDesc, srv)
}

func _Mixer_EnqueueCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MixerServer).EnqueueCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mixer_EnqueueCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MixerServer).EnqueueCommand(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mixer_ServiceDesc is the grpc.ServiceDesc for Mixer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mixer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Mixer",
	HandlerType: (*MixerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnqueueCommand",
			Handler:    _Mixer_EnqueueCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mixer.proto",
}
